### ISSUE TITLE
Error: cannot open file: nimPNG

### ISSUE THREAD

**Issue by nnnnicholas** [DanielVF/evm-contract-draw#1]
I'm on an M1 Mac macOS 12.2.1. I installed `nim` with homebrew. 

When I compile, I get the following error:

```sh
% nim compile --run evm_contract_draw.nim
Hint: used config file '/opt/homebrew/Cellar/nim/1.6.4/nim/config/nim.cfg' [Conf]
Hint: used config file '/opt/homebrew/Cellar/nim/1.6.4/nim/config/config.nims' [Conf]
.........................................................
~/Development/tools/evm-contract-draw/evm_contract_draw.nim(6, 8) Error: cannot open file: nimPNG
```

Looking forward to getting this working as the visualizations look great :)

**Comment by DanielVF** [comment]
That might just be the dependency you need to install.

**Comment by iSumitBanik** [comment]
@nnnnicholas , That's the dependency to generate the image.
You can install it using this command

```bash
nimble install nimPNG
```

**Comment by DanielVF** [comment]
Update the readme in a PR and I'll gladly accept it!

**Comment by iSumitBanik** [comment]
Sure, Will do it.

**Comment by nnnnicholas** [comment]
It works! Thank you @iSumitBanik.
